(function(){
const $d=s=>document.querySelector(s);const escd=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metricByRole={'鎴愪氦鍐呭':['product_ctr','conversion_rate','orders','gmv'],'浜у搧鏁欒偛':['retention_3s','completion_rate','save_rate','product_ctr'],'鍝佺墝鍐呭':['retention_3s','completion_rate','save_rate','share_rate','like_rate','comment_rate'],'鏂板搧涓婂競':['retention_3s','completion_rate','product_ctr','orders']};
const metricLabels={views:'鎾斁閲?,retention_3s:'3绉掔暀瀛樼巼',retention_5s:'5绉掔暀瀛樼巼',completion_rate:'瀹屾挱鐜?,like_rate:'鐐硅禐鐜?,comment_rate:'璇勮鐜?,save_rate:'鏀惰棌鐜?,share_rate:'鍒嗕韩鐜?,product_ctr:'鍟嗗搧鐐瑰嚮鐜?,orders:'璁㈠崟鏁?,conversion_rate:'鎴愪氦杞寲鐜?,gmv:'GMV',refunds:'閫€娆炬暟'};
const metricKeys=Object.keys(metricLabels);const rateKeys=metricKeys.filter(k=>k.endsWith('_rate')||k.startsWith('retention_')||k==='product_ctr');
const qianchuanSeed=[{id:'QC-VID-20251228-001-A',video_id:'VID-20251228-001',data_window:'寰呯‘璁?,scope:'鐩磋惀鍏ㄥ煙鎴浘A',spend:62636.79,overall_roi:3.16,gross_gmv:197700.3,gross_orders:1058,gross_cost_per_order:59.2,net_gmv:181081.8,net_roi:2.89,net_orders:969,net_cost_per_order:64.64,analysis_summary:'鎬籖OI 3.16銆佺患鍚圧OI 3.14锛?058绗旀暣浣撴垚浜よ鍗曡鏄庣礌鏉愪笌鎶曟斁缁勫悎宸插舰鎴愯妯¤浆鍖栵紱鍑€ROI浠嶄负2.89涓斿噣璁㈠崟969銆傚唴瀹逛晶鐨勯€夋鍐茬獊銆佷笁缁村垽鏂拰瀹炵墿姣旇緝鍙兘闄嶄綆鐞嗚В涓庨€夋鎴愭湰锛屾槸鑳借窇鐨勫€欓€夊師鍥犮€?,caveat:'杩欐槸鍏宠仈鍒嗘瀽鑰岄潪鍥犳灉璇佹槑锛涜繕闇€鍚屽懆鏈熺礌鏉愬熀鍑嗭紝鎺掗櫎鍑轰环銆佸畾鍚戙€佸晢鍝佷环鏍笺€佺洿鎾壙鎺ュ拰浼樻儬鍔涘害褰卞搷銆?},{id:'QC-VID-20251228-001-B',video_id:'VID-20251228-001',data_window:'寰呯‘璁?,scope:'鍗冨窛鎶曟斁鎴浘B锛堝彛寰勫緟纭锛?,net_gmv:191959.6,net_roi:2.87,net_orders:1022,net_cost_per_order:65.44,conversion_rate:.0729,conversion_cost:59.82,impressions:668162,cpm:100.09,clicks:15330,click_rate:.0229,avg_click_cost:4.36,plays:590764,completion_rate:.0363,five_second_play_rate:.4692,analysis_summary:'66.82涓囨洕鍏夊甫鏉?.53涓囩偣鍑伙紝鐐瑰嚮鐜?.29%锛岃鏄庣礌鏉愬叿澶囪幏寰楃偣鍑荤殑鑳藉姏锛?.29%杞寲鐜囦笌1022绗斿噣璁㈠崟璇存槑鐐瑰嚮鍚庣殑鍟嗗搧鍜岀洿鎾壙鎺ユ湁鏁堛€?6.92%鐨勪簲绉掓挱鏀剧巼鏀寔寮€澶撮€夋嫨鍐茬獊鍏锋湁鍋滅暀鑳藉姏锛屼絾3.63%瀹屾挱鐜囧亸浣庛€?,caveat:'鏈夋晥鎾斁鐜?.00%鍙兘鏄瓧娈电己澶辨垨鍙ｅ緞闂锛涗袱寮犳埅鍥剧殑鍑€鎴愪氦鏁版嵁涓嶅悓锛屽繀椤昏ˉ鍏呮棩鏈熻寖鍥淬€佽鍒掔被鍨嬪拰褰掑洜绐楀彛鍚庡啀妯悜姣旇緝銆?}];
const median=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const qianchuanCombined=[{...qianchuanSeed[0],...qianchuanSeed[1],id:'QC-VID-20251228-001',scope:'鐩磋惀鍏ㄥ煙锛堜袱寮犳í鍚戞埅鍥惧悎骞讹級',spend:62636.79,overall_roi:3.16,gross_gmv:197700.3,gross_orders:1058,gross_cost_per_order:59.2,net_gmv:191959.6,net_roi:2.87,net_orders:1022,net_cost_per_order:65.44,analysis_summary:'66.82涓囨洕鍏夊甫鏉?.53涓囩偣鍑伙紝鐐瑰嚮鐜?.29%锛岀礌鏉愬叿澶囪幏寰楃偣鍑荤殑鑳藉姏锛?6.92%鐨勪簲绉掓挱鏀剧巼璇存槑寮€澶撮€夋嫨鍐茬獊鑳芥壙鎺ョ涓€杞仠鐣欍€?.29%杞寲鐜囥€?058绗旀暣浣撴垚浜よ鍗曚笌3.16鏁翠綋ROI琛ㄦ槑鍟嗗搧鍜岀洿鎾壙鎺ュ舰鎴愯妯¤浆鍖栵紱鍑€ROI浠嶄负2.87锛岃鏄庢墸闄ゆ棤鏁堟垚浜ゅ悗浠嶅叿澶囨寔缁姇鏀惧熀纭€銆?.63%瀹屾挱鐜囧亸浣庯紝鎰忓懗鐫€绱犳潗浠峰€间富瑕侀泦涓湪鍓嶄腑娈点€?,caveat:'杩橀渶琛ュ厖缁熻鏃ユ湡銆佽鍒掔被鍨嬨€佸綊鍥犵獥鍙ｅ強鍚岃处鎴风礌鏉愬熀鍑嗭紱涓ゅ鍚屽悕鍑€鎴愪氦鎸囨爣瀛樺湪宸紓锛屾湭纭鍓嶇姝㈢敤浜庣簿纭í鍚戞帓鍚嶃€?}];
function compute(data){
 const videos=data.videos||[],metrics=data.metrics||[],features=data.features||[],experiments=data.experiments||[];const vm=new Map(videos.map(v=>[v.id,v]));const mm=new Map();metrics.forEach(m=>{if(!mm.has(m.video_id))mm.set(m.video_id,[]);mm.get(m.video_id).push(m)});const baselines={};
 Object.keys(metricByRole).forEach(role=>['24h','72h','7d'].forEach(cp=>{const rows=metrics.filter(m=>m.checkpoint===cp&&vm.get(m.video_id)?.content_role===role);baselines[role+'|'+cp]={};metricByRole[role].forEach(k=>baselines[role+'|'+cp][k]=median(rows.map(r=>Number(r[k]))));}));
 const groups=new Map();features.forEach(f=>{const v=vm.get(f.video_id);if(!v)return;const key=v.content_role+'|'+f.structure_signature;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(f)});
 const reusable=[...groups].map(([key,items])=>{const role=key.split('|')[0],sig=key.slice(role.length+1),seven=items.map(f=>(mm.get(f.video_id)||[]).find(m=>m.checkpoint==='7d')).filter(Boolean),primary=metricByRole[role]||['retention_3s'],base=baselines[role+'|7d']||{};const scores=seven.map(r=>mean(primary.map(k=>base[k]>0&&Number.isFinite(Number(r[k]))?Number(r[k])/base[k]-1:null).filter(Number.isFinite))).filter(Number.isFinite),up=median(scores),wins=scores.filter(x=>x>0).length;let status='鏁版嵁涓嶈冻';if(seven.length&&seven.length<3)status='寰呴獙璇?;else if(seven.length>=3&&up>=.10&&wins/seven.length>=2/3)status='鍙鐢?;else if(seven.length>=3&&up>0)status='鍊欓€夌粨鏋?;else if(seven.length>=3&&up<=-.10)status='楠岃瘉澶辫触';else if(seven.length>=3)status='寰呴獙璇?;const f=items[0];return {role,sig,status,samples:items.length,seven:seven.length,uplift:up,metrics:primary,audience:f.audience_type,chain:`${f.hook_type} 鈫?${f.product_judgment} 鈫?${f.proof_type} 鈫?${f.transaction_reason}`}}).sort((a,b)=>b.seven-a.seven||b.samples-a.samples);
 const variations=features.map(f=>{const v=vm.get(f.video_id)||{};return {title:v.title||v.source_filename||f.video_id,role:v.content_role||'鏈煡',keep:`淇濈暀锛?{f.audience_type}銆?{f.product_judgment}銆?{f.proof_type}`,change:`鍙浛鎹細${f.hook_type}鎴?{f.cta_type}涓殑涓€涓彉閲廯,metric:(metricByRole[v.content_role]||['retention_3s'])[0]}});
 const rows=videos.map(v=>({v,f:features.find(x=>x.video_id===v.id)})).filter(x=>x.f),rolePools=[...new Set(rows.map(x=>x.v.content_role))].map(role=>rows.filter(x=>x.v.content_role===role)).filter(x=>x.length>=2);
 const outputs=Array.from({length:Math.min(5,rows.length)},(_,i)=>{const preferred=rolePools[i%Math.max(rolePools.length,1)]||rows,ordered=[...preferred,...rows.filter(x=>!preferred.includes(x))],p=[];for(let n=0;n<ordered.length&&p.length<4;n++){const x=ordered[(i+n)%ordered.length];if(!p.some(y=>y.v.id===x.v.id))p.push(x)}const [a,j,pr,c=a]=p;return {status:'娴嬭瘯绋?,inference_type:'澶氳棰戠粍鍚堟帹绠?,title:`${a.f.audience_type}锛氶獙璇佲€?{a.f.conflict_type}鈥漙,role:a.v.content_role,audience:a.f.audience_type,opening:`鍏堢偣鍑衡€?{a.f.conflict_type}鈥濓紝鐢?{a.f.hook_type}鍒堕€犻€夋嫨鍘嬪姏`,judgment:j.f.product_judgment,proof:`鎷嶆憚${pr.f.proof_type}锛岀敤浜庨獙璇佷笂杩板垽鏂璥,cta:`浠?{c.f.transaction_reason}鎵挎帴锛屽苟浣跨敤${c.f.cta_type}`,source_count:new Set(p.map(x=>x.v.id)).size,source_video_ids:[...new Set(p.map(x=>x.v.id))],basis:`缁勫悎鎺ㄧ畻锛氫汉缇や笌鍐茬獊鏉ヨ嚜${a.v.source_filename}锛涗骇鍝佸垽鏂潵鑷?{j.v.source_filename}锛涜瘉鏄庢柟寮忔潵鑷?{pr.v.source_filename}锛涙垚浜ゆ壙鎺ユ潵鑷?{c.v.source_filename}銆備笉鏄幇鏈夊崟鏉¤棰戞憳褰曘€俙,challenge:'璺ㄨ棰戠粍浠剁粍鍚堝皻鏈鏁版嵁楠岃瘉锛岄渶妫€鏌ヤ骇鍝併€佸満鏅拰浜虹兢鍏煎鎬с€?}});
 return {reusable,variations,outputs,experiments};
}
function statusClass(s){return s==='鍙鐢??'good':s==='楠岃瘉澶辫触'?'bad':s==='鍊欓€夌粨鏋??'candidate':'pending'}
function render(data){const d=data.decisions||compute(data);
 $d('#reuseGrid').innerHTML=d.reusable.map(x=>`<article class="decision-card"><div class="decision-top"><span>${escd(x.role||x.content_role)}</span><b class="status ${statusClass(x.status)}">${escd(x.status)}</b></div><h3>${escd(x.sig||x.structure_signature)}</h3><p class="decision-chain">${escd(x.chain)}</p><dl><div><dt>閫傜敤浜虹兢</dt><dd>${escd(x.audience)}</dd></div><div><dt>鏍锋湰/7澶╂暟鎹?/dt><dd>${x.samples??x.sample_count} / ${x.seven??x.seven_day_count}</dd></div><div><dt>鏍稿績鎸囨爣</dt><dd>${(x.metrics||x.primary_metrics||[]).map(k=>metricLabels[k]||k).join('銆?)}</dd></div><div><dt>涓綅鎻愬崌</dt><dd>${x.uplift==null&&x.median_uplift==null?'寰呭洖濉?:((x.uplift??x.median_uplift)*100).toFixed(1)+'%'}</dd></div></dl><aside>璐ㄧ枒锛氱粨鏋滄槸鍚︾敱娴侀噺銆佸彂甯冩椂闂淬€佷环鏍笺€佷富鎾垨浼樻儬閫犳垚锛?/aside></article>`).join('')||'<div class="empty">灏氭棤缁撴瀯鐗瑰緛</div>';
 $d('#experimentGrid').innerHTML=(d.experiments||[]).map(x=>`<article class="experiment-card"><div class="decision-top"><span>${escd(x.content_role)}</span><b class="status pending">${escd(x.status)}</b></div><h3>${escd(x.title)}</h3><p><strong>鍋囪锛?/strong>${escd(x.hypothesis)}</p><p class="challenge"><strong>鍙嶅悜璐ㄧ枒锛?/strong>${escd(x.challenge)}</p><div class="ab-grid"><div><b>A 瀵圭収</b><span>${escd(x.control_design)}</span></div><div><b>B 鍙橀噺</b><span>${escd(x.variant_design)}</span></div></div><footer>涓绘寚鏍囷細${escd(metricLabels[x.primary_metric]||x.primary_metric)} 路 姣忕増鑷冲皯${x.required_per_variant}鏉?/footer></article>`).join('')||'<div class="empty">鏆傛棤瀹為獙鏂规</div>';
 $d('#variationGrid').innerHTML=(d.variations||[]).slice(0,9).map(x=>`<article class="decision-card compact-card"><div class="decision-top"><span>${escd(x.role||x.content_role)}</span><b class="status pending">瀹為獙鏂瑰悜</b></div><h3>${escd(x.title)}</h3><p>${escd(x.keep)}</p><p>${escd(x.change)}</p><footer>瑙傚療锛?{escd(metricLabels[x.metric||x.primary_metric]||x.metric||x.primary_metric)}</footer></article>`).join('');
 $d('#outputGrid').innerHTML=(d.outputs||[]).map(x=>`<article class="output-card"><div class="decision-top"><span>${escd(x.role||x.content_role)}</span><b class="status pending">${escd(x.status||'娴嬭瘯绋?)}</b></div><p class="inference-badge">${escd(x.inference_type||'澶氳棰戠粍鍚堟帹绠?)} 路 ${x.source_count||x.source_video_ids?.length||'澶?}鏉℃潵婧?/p><h3>${escd(x.title)}</h3><ol><li><b>鐩爣浜虹兢</b><span>${escd(x.audience)}</span></li><li><b>寮€澶村啿绐?/b><span>${escd(x.opening)}</span></li><li><b>浜у搧鍒ゆ柇</b><span>${escd(x.judgment||x.product_judgment)}</span></li><li><b>璇佹槑闀滃ご</b><span>${escd(x.proof)}</span></li><li><b>鎴愪氦鎵挎帴</b><span>${escd(x.cta||x.conversion)}</span></li></ol><footer>${escd(x.basis)}</footer>${x.challenge?`<aside>璐ㄧ枒锛?{escd(x.challenge)}</aside>`:''}</article>`).join('')||'<div class="empty">鏆傛棤鍐呭寤鸿</div>';
 setupEntry(data.videos||[]);
 const original=window.renderDetail;if(original&&!original.__decisionWrapped){const wrapped=function(){original();appendVideoDecision(data);appendQianchuan(data)};wrapped.__decisionWrapped=true;window.renderDetail=wrapped;appendVideoDecision(data);appendQianchuan(data);}
}
function money(v){return v==null?'鈥?:'楼'+Number(v).toLocaleString('zh-CN',{maximumFractionDigits:2})}function pct(v){return v==null?'鈥?:(Number(v)*100).toFixed(2)+'%'}
function appendQianchuan(data){const v=typeof state==='undefined'?null:state.videos?.find(x=>x.id===state.activeId),box=$d('#videoDetail');if(!v||!box||box.querySelector('.qianchuan-analysis'))return;const rows=(data.qianchuan?.length?data.qianchuan:qianchuanCombined).filter(x=>x.video_id===v.id);if(!rows.length)return;box.insertAdjacentHTML('beforeend',`<section class="qianchuan-analysis"><h3>鍗冨窛鏁版嵁鍒嗘瀽</h3><p class="data-empty">鐙珛鎶曟斁蹇収锛屼笉涓?4灏忔椂/72灏忔椂/7澶╄嚜鐒跺唴瀹规寚鏍囨贩绠椼€傜粺璁＄獥鍙ｏ細${escd(rows[0].data_window)}</p>${rows.map(q=>`<article class="qc-card"><div class="decision-top"><span>${escd(q.scope)}</span><b class="status pending">鍙ｅ緞寰呯‘璁?/b></div><div class="qc-metrics"><span>娑堣€?b>${money(q.spend)}</b></span><span>ROI<b>${q.overall_roi??q.net_roi??'鈥?}</b></span><span>鎴愪氦閲戦<b>${money(q.gross_gmv??q.net_gmv)}</b></span><span>璁㈠崟<b>${q.gross_orders??q.net_orders??'鈥?}</b></span><span>鏇濆厜<b>${q.impressions==null?'鈥?:Number(q.impressions).toLocaleString()}</b></span><span>鐐瑰嚮鐜?b>${pct(q.click_rate)}</b></span><span>5绉掓挱鏀剧巼<b>${pct(q.five_second_play_rate)}</b></span><span>杞寲鐜?b>${pct(q.conversion_rate)}</b></span></div><h4>涓轰粈涔堣兘璺?/h4><p>${escd(q.analysis_summary)}</p><aside>璐ㄧ枒锛?{escd(q.caveat)}</aside></article>`).join('')}</section>`)}
function appendVideoDecision(data){const v=typeof state==='undefined'?null:state.videos?.find(x=>x.id===state.activeId);const box=$d('#videoDetail');if(!v||!box||box.querySelector('.video-decision'))return;const f=(data.features||[]).find(x=>x.video_id===v.id),ms=(data.metrics||[]).filter(x=>x.video_id===v.id).sort((a,b)=>String(a.checkpoint).localeCompare(String(b.checkpoint)));if(!f)return;box.insertAdjacentHTML('beforeend',`<section class="video-decision"><h3>缁撴瀯鐗瑰緛</h3><div class="feature-tags"><span>${escd(f.audience_type)}</span><span>${escd(f.conflict_type)}</span><span>${escd(f.hook_type)}</span><span>${escd(f.proof_type)}</span><span>${escd(f.cta_type)}</span></div><h3>鎸囨爣蹇収</h3>${ms.length?`<div class="snapshot-table">${ms.map(m=>`<div><b>${escd(m.checkpoint)}</b><span>鎾斁 ${m.views??'鈥?}</span><span>3绉?${m.retention_3s==null?'鈥?:(m.retention_3s*100).toFixed(1)+'%'}</span><span>鐐瑰嚮 ${m.product_ctr==null?'鈥?:(m.product_ctr*100).toFixed(1)+'%'}</span><span>璁㈠崟 ${m.orders??'鈥?}</span></div>`).join('')}</div>`:'<p class="data-empty">鏁版嵁涓嶈冻锛氬皻鏈洖濉?4灏忔椂銆?2灏忔椂鎴?澶╂寚鏍囷紝涓嶈兘鍒ゆ柇缁撴瀯鏈夋晥銆?/p>'}<h3>涓夐」鍒ゆ柇</h3><div class="mini-decisions"><div><b>澶嶇敤</b><span>鏁版嵁涓嶈冻锛屼繚鐣欎负寰呴獙璇佸亣璁?/span></div><div><b>瑁傚彉</b><span>涓€娆″彧鏇挎崲涓€涓厓绱犲苟鍋欰/B娴嬭瘯</span></div><div><b>杈撳嚭</b><span>褰撳墠鍙兘鐢熸垚娴嬭瘯绋匡紝涓嶈兘鏍囪鎺ㄨ崘鎷嶆憚</span></div></div><aside class="challenge-box"><b>璐ㄧ枒涓庢祴璇?/b><p>闇€鎺掗櫎娴侀噺銆佸彂甯冩椂闂淬€佷环鏍笺€佷富鎾拰浼樻儬宸紓锛汚/B鍚勮嚦灏?鏉★紝24灏忔椂鍒濆垽銆?2灏忔椂澶嶆牳銆?澶╁畾璁恒€?/p></aside></section>`)}
const columns=['id','video_id','checkpoint','captured_at',...metricKeys,'negative_feedback','publish_time','traffic_note'];let drafts=[];
function setupEntry(videos){if($d('#metricVideo').dataset.ready)return;$d('#metricVideo').dataset.ready='1';$d('#metricVideo').innerHTML=videos.map(v=>`<option value="${escd(v.id)}">${escd(v.source_filename)} 路 ${escd(v.id)}</option>`).join('');$d('#metricFields').innerHTML=metricKeys.map(k=>`<label>${metricLabels[k]}<input name="${k}" type="number" min="0" ${rateKeys.includes(k)?'max="1" step="0.001"':'step="0.01"'} placeholder="${rateKeys.includes(k)?'0-1':''}"></label>`).join('');$d('#metricForm').addEventListener('submit',e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));raw.captured_at=new Date(raw.captured_at).toISOString();raw.id=`MET-${raw.video_id}-${raw.checkpoint}-${Date.now()}`;const result=validateRow(raw,videos);if(result.length){$d('#metricMessage').textContent=result.join('锛?);return}drafts.push(raw);updateDrafts();e.currentTarget.reset();$d('#metricMessage').textContent='宸插姞鍏ュ緟瀵煎嚭鏁版嵁銆?});$d('#metricFile').addEventListener('change',async e=>{const text=await e.target.files[0]?.text();if(!text)return;const rows=parseCsv(text),errors=[],valid=[];rows.forEach((r,i)=>{const er=validateRow(r,videos);er.length?errors.push(`绗?{i+2}琛岋細${er.join('锛?)}`):valid.push(r)});drafts.push(...valid);updateDrafts();$d('#importResult').innerHTML=`<strong>${valid.length}鏉″悎娉曪紝${errors.length}鏉￠敊璇?/strong>${errors.length?`<ul>${errors.map(x=>`<li>${escd(x)}</li>`).join('')}</ul>`:''}`});$d('#downloadTemplate').addEventListener('click',e=>{e.preventDefault();download('\ufeff'+columns.join(',')+'\r\n','metric_import_template.csv')});$d('#exportDrafts').addEventListener('click',e=>{e.preventDefault();if(!drafts.length){$d('#importResult').textContent='娌℃湁鍙鍑虹殑鍚堟硶鏁版嵁';return}download('\ufeff'+[columns.join(','),...drafts.map(r=>columns.map(c=>csvCell(r[c])).join(','))].join('\r\n'),'metric_snapshots_validated.csv')})}
function updateDrafts(){$d('#draftCount').textContent=`${drafts.length}鏉″緟瀵煎嚭`}
function validateRow(r,videos){const e=[];if(!videos.some(v=>v.id===r.video_id))e.push('鏈煡瑙嗛ID');if(!['24h','72h','7d'].includes(r.checkpoint))e.push('鏁版嵁绐楀彛蹇呴』涓?4h銆?2h鎴?d');if(!r.captured_at||Number.isNaN(Date.parse(r.captured_at)))e.push('閲囬泦鏃堕棿鏃犳晥');rateKeys.forEach(k=>{if(r[k]!==''&&r[k]!=null&&(Number(r[k])<0||Number(r[k])>1||!Number.isFinite(Number(r[k]))))e.push(`${metricLabels[k]}蹇呴』鍦?鍒?涔嬮棿`)});metricKeys.filter(k=>!rateKeys.includes(k)).forEach(k=>{if(r[k]!==''&&r[k]!=null&&(Number(r[k])<0||!Number.isFinite(Number(r[k]))))e.push(`${metricLabels[k]}涓嶈兘涓鸿礋鏁癭)});return e}
function parseCsv(t){const rows=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'&&t[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=(rows.shift()||[]).map(x=>x.replace(/^\ufeff/,''));return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]||''])))}function csvCell(v){v=v??'';v=String(v);return /[",\r\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v}function download(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function init(){try{const url=location.hostname.endsWith('github.io')?'./data/bootstrap.json':'/api/bootstrap?limit=100';const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('璇诲彇澶辫触');render(await r.json())}catch(e){['#reuseGrid','#experimentGrid','#variationGrid','#outputGrid'].forEach(s=>{const el=$d(s);if(el)el.innerHTML='<div class="empty">鍐崇瓥鏁版嵁鏆備笉鍙敤</div>'})}}
document.addEventListener('DOMContentLoaded',init);
})();

