(function(){
const $d=s=>document.querySelector(s);const escd=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metricByRole={'成交内容':['product_ctr','conversion_rate','orders','gmv'],'产品教育':['retention_3s','completion_rate','save_rate','product_ctr'],'品牌内容':['retention_3s','completion_rate','save_rate','share_rate','like_rate','comment_rate'],'新品上市':['retention_3s','completion_rate','product_ctr','orders']};
const metricLabels={views:'播放量',retention_3s:'3秒留存率',retention_5s:'5秒留存率',completion_rate:'完播率',like_rate:'点赞率',comment_rate:'评论率',save_rate:'收藏率',share_rate:'分享率',product_ctr:'商品点击率',orders:'订单数',conversion_rate:'成交转化率',gmv:'GMV',refunds:'退款数'};
const metricKeys=Object.keys(metricLabels);const rateKeys=metricKeys.filter(k=>k.endsWith('_rate')||k.startsWith('retention_')||k==='product_ctr');
const median=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function compute(data){
 const videos=data.videos||[],metrics=data.metrics||[],features=data.features||[],experiments=data.experiments||[];const vm=new Map(videos.map(v=>[v.id,v]));const mm=new Map();metrics.forEach(m=>{if(!mm.has(m.video_id))mm.set(m.video_id,[]);mm.get(m.video_id).push(m)});const baselines={};
 Object.keys(metricByRole).forEach(role=>['24h','72h','7d'].forEach(cp=>{const rows=metrics.filter(m=>m.checkpoint===cp&&vm.get(m.video_id)?.content_role===role);baselines[role+'|'+cp]={};metricByRole[role].forEach(k=>baselines[role+'|'+cp][k]=median(rows.map(r=>Number(r[k]))));}));
 const groups=new Map();features.forEach(f=>{const v=vm.get(f.video_id);if(!v)return;const key=v.content_role+'|'+f.structure_signature;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(f)});
 const reusable=[...groups].map(([key,items])=>{const role=key.split('|')[0],sig=key.slice(role.length+1),seven=items.map(f=>(mm.get(f.video_id)||[]).find(m=>m.checkpoint==='7d')).filter(Boolean),primary=metricByRole[role]||['retention_3s'],base=baselines[role+'|7d']||{};const scores=seven.map(r=>mean(primary.map(k=>base[k]>0&&Number.isFinite(Number(r[k]))?Number(r[k])/base[k]-1:null).filter(Number.isFinite))).filter(Number.isFinite),up=median(scores),wins=scores.filter(x=>x>0).length;let status='数据不足';if(seven.length&&seven.length<3)status='待验证';else if(seven.length>=3&&up>=.10&&wins/seven.length>=2/3)status='可复用';else if(seven.length>=3&&up>0)status='候选结构';else if(seven.length>=3&&up<=-.10)status='验证失败';else if(seven.length>=3)status='待验证';const f=items[0];return {role,sig,status,samples:items.length,seven:seven.length,uplift:up,metrics:primary,audience:f.audience_type,chain:`${f.hook_type} → ${f.product_judgment} → ${f.proof_type} → ${f.transaction_reason}`}}).sort((a,b)=>b.seven-a.seven||b.samples-a.samples);
 const variations=features.map(f=>{const v=vm.get(f.video_id)||{};return {title:v.title||v.source_filename||f.video_id,role:v.content_role||'未知',keep:`保留：${f.audience_type}、${f.product_judgment}、${f.proof_type}`,change:`只替换：${f.hook_type}或${f.cta_type}中的一个变量`,metric:(metricByRole[v.content_role]||['retention_3s'])[0]}});
 const outputs=videos.map(v=>({v,f:features.find(x=>x.video_id===v.id)})).filter(x=>x.f).slice(0,5).map(({v,f})=>({title:`${f.audience_type}：${f.conflict_type}`,role:v.content_role,audience:v.audience,opening:v.hook_text,judgment:f.product_judgment,proof:v.proof,cta:v.intended_action,basis:`来源：${v.source_filename}；暂无运营指标，当前仅为测试稿`}));
 return {reusable,variations,outputs,experiments};
}
function statusClass(s){return s==='可复用'?'good':s==='验证失败'?'bad':s==='候选结构'?'candidate':'pending'}
function render(data){const d=data.decisions||compute(data);
 $d('#reuseGrid').innerHTML=d.reusable.map(x=>`<article class="decision-card"><div class="decision-top"><span>${escd(x.role||x.content_role)}</span><b class="status ${statusClass(x.status)}">${escd(x.status)}</b></div><h3>${escd(x.sig||x.structure_signature)}</h3><p class="decision-chain">${escd(x.chain)}</p><dl><div><dt>适用人群</dt><dd>${escd(x.audience)}</dd></div><div><dt>样本/7天数据</dt><dd>${x.samples??x.sample_count} / ${x.seven??x.seven_day_count}</dd></div><div><dt>核心指标</dt><dd>${(x.metrics||x.primary_metrics||[]).map(k=>metricLabels[k]||k).join('、')}</dd></div><div><dt>中位提升</dt><dd>${x.uplift==null&&x.median_uplift==null?'待回填':((x.uplift??x.median_uplift)*100).toFixed(1)+'%'}</dd></div></dl><aside>质疑：结果是否由流量、发布时间、价格、主播或优惠造成？</aside></article>`).join('')||'<div class="empty">尚无结构特征</div>';
 $d('#experimentGrid').innerHTML=(d.experiments||[]).map(x=>`<article class="experiment-card"><div class="decision-top"><span>${escd(x.content_role)}</span><b class="status pending">${escd(x.status)}</b></div><h3>${escd(x.title)}</h3><p><strong>假设：</strong>${escd(x.hypothesis)}</p><p class="challenge"><strong>反向质疑：</strong>${escd(x.challenge)}</p><div class="ab-grid"><div><b>A 对照</b><span>${escd(x.control_design)}</span></div><div><b>B 变量</b><span>${escd(x.variant_design)}</span></div></div><footer>主指标：${escd(metricLabels[x.primary_metric]||x.primary_metric)} · 每版至少${x.required_per_variant}条</footer></article>`).join('')||'<div class="empty">暂无实验方案</div>';
 $d('#variationGrid').innerHTML=(d.variations||[]).slice(0,9).map(x=>`<article class="decision-card compact-card"><div class="decision-top"><span>${escd(x.role||x.content_role)}</span><b class="status pending">实验方向</b></div><h3>${escd(x.title)}</h3><p>${escd(x.keep)}</p><p>${escd(x.change)}</p><footer>观察：${escd(metricLabels[x.metric||x.primary_metric]||x.metric||x.primary_metric)}</footer></article>`).join('');
 $d('#outputGrid').innerHTML=(d.outputs||[]).map(x=>`<article class="output-card"><div class="decision-top"><span>${escd(x.role||x.content_role)}</span><b class="status pending">${escd(x.status||'测试稿')}</b></div><h3>${escd(x.title)}</h3><ol><li><b>目标人群</b><span>${escd(x.audience)}</span></li><li><b>开头冲突</b><span>${escd(x.opening)}</span></li><li><b>产品判断</b><span>${escd(x.judgment||x.product_judgment)}</span></li><li><b>证明镜头</b><span>${escd(x.proof)}</span></li><li><b>成交承接</b><span>${escd(x.cta||x.conversion)}</span></li></ol><footer>${escd(x.basis)}</footer></article>`).join('')||'<div class="empty">暂无内容建议</div>';
 setupEntry(data.videos||[]);
 const original=window.renderDetail;if(original&&!original.__decisionWrapped){const wrapped=function(){original();appendVideoDecision(data)};wrapped.__decisionWrapped=true;window.renderDetail=wrapped;appendVideoDecision(data);}
}
function appendVideoDecision(data){const v=typeof state==='undefined'?null:state.videos?.find(x=>x.id===state.activeId);const box=$d('#videoDetail');if(!v||!box||box.querySelector('.video-decision'))return;const f=(data.features||[]).find(x=>x.video_id===v.id),ms=(data.metrics||[]).filter(x=>x.video_id===v.id).sort((a,b)=>String(a.checkpoint).localeCompare(String(b.checkpoint)));if(!f)return;box.insertAdjacentHTML('beforeend',`<section class="video-decision"><h3>结构特征</h3><div class="feature-tags"><span>${escd(f.audience_type)}</span><span>${escd(f.conflict_type)}</span><span>${escd(f.hook_type)}</span><span>${escd(f.proof_type)}</span><span>${escd(f.cta_type)}</span></div><h3>指标快照</h3>${ms.length?`<div class="snapshot-table">${ms.map(m=>`<div><b>${escd(m.checkpoint)}</b><span>播放 ${m.views??'—'}</span><span>3秒 ${m.retention_3s==null?'—':(m.retention_3s*100).toFixed(1)+'%'}</span><span>点击 ${m.product_ctr==null?'—':(m.product_ctr*100).toFixed(1)+'%'}</span><span>订单 ${m.orders??'—'}</span></div>`).join('')}</div>`:'<p class="data-empty">数据不足：尚未回填24小时、72小时或7天指标，不能判断结构有效。</p>'}<h3>三项判断</h3><div class="mini-decisions"><div><b>复用</b><span>数据不足，保留为待验证假设</span></div><div><b>裂变</b><span>一次只替换一个元素并做A/B测试</span></div><div><b>输出</b><span>当前只能生成测试稿，不能标记推荐拍摄</span></div></div><aside class="challenge-box"><b>质疑与测试</b><p>需排除流量、发布时间、价格、主播和优惠差异；A/B各至少3条，24小时初判、72小时复核、7天定论。</p></aside></section>`)}
const columns=['id','video_id','checkpoint','captured_at',...metricKeys,'negative_feedback','publish_time','traffic_note'];let drafts=[];
function setupEntry(videos){if($d('#metricVideo').dataset.ready)return;$d('#metricVideo').dataset.ready='1';$d('#metricVideo').innerHTML=videos.map(v=>`<option value="${escd(v.id)}">${escd(v.source_filename)} · ${escd(v.id)}</option>`).join('');$d('#metricFields').innerHTML=metricKeys.map(k=>`<label>${metricLabels[k]}<input name="${k}" type="number" min="0" ${rateKeys.includes(k)?'max="1" step="0.001"':'step="0.01"'} placeholder="${rateKeys.includes(k)?'0-1':''}"></label>`).join('');$d('#metricForm').addEventListener('submit',e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));raw.captured_at=new Date(raw.captured_at).toISOString();raw.id=`MET-${raw.video_id}-${raw.checkpoint}-${Date.now()}`;const result=validateRow(raw,videos);if(result.length){$d('#metricMessage').textContent=result.join('；');return}drafts.push(raw);updateDrafts();e.currentTarget.reset();$d('#metricMessage').textContent='已加入待导出数据。'});$d('#metricFile').addEventListener('change',async e=>{const text=await e.target.files[0]?.text();if(!text)return;const rows=parseCsv(text),errors=[],valid=[];rows.forEach((r,i)=>{const er=validateRow(r,videos);er.length?errors.push(`第${i+2}行：${er.join('；')}`):valid.push(r)});drafts.push(...valid);updateDrafts();$d('#importResult').innerHTML=`<strong>${valid.length}条合法，${errors.length}条错误</strong>${errors.length?`<ul>${errors.map(x=>`<li>${escd(x)}</li>`).join('')}</ul>`:''}`});$d('#downloadTemplate').addEventListener('click',e=>{e.preventDefault();download('\ufeff'+columns.join(',')+'\r\n','metric_import_template.csv')});$d('#exportDrafts').addEventListener('click',e=>{e.preventDefault();if(!drafts.length){$d('#importResult').textContent='没有可导出的合法数据';return}download('\ufeff'+[columns.join(','),...drafts.map(r=>columns.map(c=>csvCell(r[c])).join(','))].join('\r\n'),'metric_snapshots_validated.csv')})}
function updateDrafts(){$d('#draftCount').textContent=`${drafts.length}条待导出`}
function validateRow(r,videos){const e=[];if(!videos.some(v=>v.id===r.video_id))e.push('未知视频ID');if(!['24h','72h','7d'].includes(r.checkpoint))e.push('数据窗口必须为24h、72h或7d');if(!r.captured_at||Number.isNaN(Date.parse(r.captured_at)))e.push('采集时间无效');rateKeys.forEach(k=>{if(r[k]!==''&&r[k]!=null&&(Number(r[k])<0||Number(r[k])>1||!Number.isFinite(Number(r[k]))))e.push(`${metricLabels[k]}必须在0到1之间`)});metricKeys.filter(k=>!rateKeys.includes(k)).forEach(k=>{if(r[k]!==''&&r[k]!=null&&(Number(r[k])<0||!Number.isFinite(Number(r[k]))))e.push(`${metricLabels[k]}不能为负数`)});return e}
function parseCsv(t){const rows=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'&&t[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=(rows.shift()||[]).map(x=>x.replace(/^\ufeff/,''));return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]||''])))}function csvCell(v){v=v??'';v=String(v);return /[",\r\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v}function download(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function init(){try{const url=location.hostname.endsWith('github.io')?'./data/bootstrap.json':'/api/bootstrap?limit=100';const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('读取失败');render(await r.json())}catch(e){['#reuseGrid','#experimentGrid','#variationGrid','#outputGrid'].forEach(s=>{const el=$d(s);if(el)el.innerHTML='<div class="empty">决策数据暂不可用</div>'})}}
document.addEventListener('DOMContentLoaded',init);
})();
